<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BrowserDesk</AssemblyName>
    <RootNamespace>BrowserDesk</RootNamespace>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\Assets\Fonts\Vazirmatn.ttf">
      <Link>Assets\Fonts\Vazirmatn.ttf</Link>
    </Resource>
  </ItemGroup>
</Project>
